services:

  api:
    build: ./business/
    container_name: mybus-api
    volumes:
      - ./business/src:/api/src
    ports:
      - "${API_PORT}:80"
    env_file:
      - .env
    tty: true
    depends_on:
      - database
    networks:
      - api-to-database

  database:
    image: postgres:15
    container_name: mybus-database
    env_file:
      - .env
    environment:
      POSTGRES_DB: myBus
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - api-to-database

networks:
  api-to-database: