# Usa a imagem completa do SDK (tem dotnet watch)
FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /business
COPY . ./

# Expõe a porta
EXPOSE 80

# Usa o "dotnet watch" para hot reload
ENTRYPOINT ["dotnet", "watch", "run"]

